services:
  cellar:
    image: postgres:16-alpine
    networks:
      - dragon_tap
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dragon_tap_data:/var/lib/postgresql/data
      - ./cellar/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  innkeeper-java:
    build: ./innkeeper-java
    networks:
      - dragon_tap
    environment:
      SERVER_PORT: ${INNKEEPER_PORT}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_DATABASE_PLATFORM:  ${SPRING_JPA_DATABASE_PLATFORM}
    depends_on:
      - cellar

  board-react:
    build:
      context: ./board-react
      args:
        VITE_API_URL: ${VITE_API_URL}
    networks:
      - dragon_tap

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - innkeeper-java
      - board-react
    networks:
      - dragon_tap

networks:
  dragon_tap:
    driver: bridge

volumes:
  dragon_tap_data: