events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://board-react:4184/;
    }

    location /api/ {
      proxy_pass http://innkeeper-java:4181/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}